//Zelda Expansion Disk
//By LuigiBlood

//Uses ARM9 bass

//RAM Usage

constant DDHOOK_RAM(0x80410000)		//CODE
constant DDHOOK_GPRAM(0x80420000)	//GENERAL PURPOSE
	constant DDHOOK_ADDRTABLE(DDHOOK_GPRAM+0)		//ADDRESS TABLE
	constant DDHOOK_TEXTTABLE(DDHOOK_GPRAM+0x10000)		//ENGLISH TEXT TABLE (DDHOOK_MESSAGETABLENES)
	constant DDHOOK_TEXTDATA(DDHOOK_GPRAM+0x20000)		//ENGLISH TEXT DATA (DDHOOK_NESTEST)